# -*- coding: utf-8 -*-
"""clientes 2026 varios.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ehcarjsTh4hjEpNkluCLkprTbjYzfFvF
"""

# 1. Importar librerías
import pandas as pd
import glob # Librería necesaria para encontrar archivos

# Lista para acumular todos los datos
dfs = []

# Obtener una lista de todos los archivos .txt en el directorio /content/
file_paths = glob.glob('/content/*.txt') # Cambiado de archivos subidos a búsqueda de archivos existentes

# 3. Procesar cada TXT (tratándolos como CSV)
for archivo in file_paths: # Iterar sobre la lista de rutas de archivos
    print(f"Processing file: {archivo}")
    try:
        # Leer TXT (asumiendo tab como separador y latin1 como codificación)
        df = pd.read_csv(archivo, sep='\t', encoding='latin1')

        # Eliminar espacios en blanco de los nombres de las columnas
        df.columns = df.columns.str.strip()

        # Renombrar columnas para que coincidan con los nombres esperados
        df = df.rename(columns={
            "RUC_EMISOR": "RUC",
            "RAZON_SOCIAL_EMISOR": "PROVEEDOR",
            "FECHA_EMISION": "FECHA", # Renombrar FECHA_EMISION a FECHA
            "VALOR_SIN_IMPUESTOS": "VALOR SIN IMPUESTOS", # Renombrar VALOR_SIN_IMPUESTOS a VALOR SIN IMPUESTOS
            "CLAVE_ACCESO": "FACT", # Asumiendo FACT corresponde a CLAVE_ACCESO
            "IMPORTE_TOTAL": "TOTAL"
        })

        # Convertir columnas numéricas
        df["IVA"] = pd.to_numeric(df["IVA"], errors="coerce").fillna(0)
        df["VALOR SIN IMPUESTOS"] = pd.to_numeric(
            df["VALOR SIN IMPUESTOS"], errors="coerce"
        ).fillna(0)

        # Convertir FECHA a formato fecha
        df["FECHA"] = pd.to_datetime(df["FECHA"], errors="coerce", dayfirst=True)

        # Crear BASE 0% y BASE 12%
        df["BASE 0%"] = df.apply(
            lambda x: x["VALOR SIN IMPUESTOS"] if x["IVA"] == 0 else 0,
            axis=1
        )

        df["BASE 12%"] = df.apply(
            lambda x: x["VALOR SIN IMPUESTOS"] if x["IVA"] != 0 else 0,
            axis=1
        )

        # Crear columnas faltantes si no existen y se necesitan para la salida
        columnas_necesarias_output = [
            "PROVEEDOR",
            "RUC",
            "FACT",
            "NO OBJETO",
            "EXCENTO IVA",
            "PROPINA",
            "TOTAL"
        ]

        for col in columnas_necesarias_output:
            if col not in df.columns:
                df[col] = 0

        # Ordenar columnas finales
        columnas_ordenadas = [
            "FECHA",
            "PROVEEDOR",
            "RUC",
            "FACT",
            "NO OBJETO",
            "EXCENTO IVA",
            "BASE 0%",
            "BASE 12%",
            "PROPINA",
            "IVA",
            "TOTAL"
        ]

        # Asegurarse de que todas las columnas para el orden final existan
        for col in columnas_ordenadas:
            if col not in df.columns:
                df[col] = 0 # Agregarlas si faltan antes de seleccionar y reordenar

        df = df[columnas_ordenadas]

        # Agregar al acumulador
        dfs.append(df)
    except Exception as e:
        print(f"Error processing {archivo}: {e}")

# 4. Unir todos los DataFrames en un solo DataFrame
df_final = pd.concat(dfs, ignore_index=True)

# 5. Crear columna MES-AÑO para agrupar
df_final["MES"] = df_final["FECHA"].dt.to_period("M").astype(str)

# 6. Crear el Excel con una hoja por mes
nombre_excel = "compras_separadas_por_mes.xlsx"

with pd.ExcelWriter(nombre_excel, engine="xlsxwriter") as writer:
    for mes, df_mes in df_final.groupby("MES"):
        df_mes.drop(columns="MES").to_excel(
            writer,
            sheet_name=mes,
            index=False
        )

# 7. Descargar el Excel final
from google.colab import files
files.download(nombre_excel)

